/*
 * Copyright 2014 Loic Petit
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package fr.petitl.antichamber.gui.panels;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 */
public class TriggerTrackerPanel {
    private final TriggerTableModel model;
    private JTable triggerTable;
    private JPanel content;
    private JCheckBox gunsCheckBox;
    private JCheckBox signsCheckBox;
    private JCheckBox pinkCubesCheckBox;
    private JCheckBox mapCheckBox;
    private JCheckBox creditsCheckBox;
    private JScrollPane scroll;

    public TriggerTrackerPanel() {
        model = new TriggerTableModel();
        triggerTable.setModel(model);
        ActionListener onCheckbox = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                model.filter(gunsCheckBox.isSelected(), signsCheckBox.isSelected(), pinkCubesCheckBox.isSelected(), mapCheckBox.isSelected(), creditsCheckBox.isSelected());
            }
        };
        gunsCheckBox.addActionListener(onCheckbox);
        signsCheckBox.addActionListener(onCheckbox);
        pinkCubesCheckBox.addActionListener(onCheckbox);
        mapCheckBox.addActionListener(onCheckbox);
        creditsCheckBox.addActionListener(onCheckbox);
        onCheckbox.actionPerformed(null);
        scroll.getViewport().setBackground(Color.BLACK);
        triggerTable.getColumnModel().getColumn(0).setMaxWidth(250);
    }

    public JPanel getContent() {
        return content;
    }

    public TriggerTableModel getModel() {
        return model;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        content = new JPanel();
        content.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        content.add(panel1, BorderLayout.NORTH);
        gunsCheckBox = new JCheckBox();
        gunsCheckBox.setSelected(true);
        gunsCheckBox.setText("Guns");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(gunsCheckBox, gbc);
        signsCheckBox = new JCheckBox();
        signsCheckBox.setSelected(true);
        signsCheckBox.setText("Signs");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(signsCheckBox, gbc);
        pinkCubesCheckBox = new JCheckBox();
        pinkCubesCheckBox.setSelected(true);
        pinkCubesCheckBox.setText("Pink Cubes");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(pinkCubesCheckBox, gbc);
        mapCheckBox = new JCheckBox();
        mapCheckBox.setText("Map");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(mapCheckBox, gbc);
        creditsCheckBox = new JCheckBox();
        creditsCheckBox.setSelected(true);
        creditsCheckBox.setText("Credits");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(creditsCheckBox, gbc);
        scroll = new JScrollPane();
        content.add(scroll, BorderLayout.CENTER);
        triggerTable = new JTable();
        triggerTable.setBackground(new Color(-16777216));
        triggerTable.setFont(new Font(triggerTable.getFont().getName(), triggerTable.getFont().getStyle(), 14));
        triggerTable.setForeground(new Color(-1));
        triggerTable.setGridColor(new Color(-3355444));
        scroll.setViewportView(triggerTable);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return content;
    }
}
